name: Generate metrics

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - .github/workflows/metrics.yml

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_display: large
          config_octicon: yes
          config_timezone: Europe/Warsaw
          config_twemoji: yes
          plugin_languages_analysis_timeout: 120
          plugin_languages_analysis_timeout_repositories: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages: yes
          plugin_languages_limit: 50
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_other: no
          plugin_languages_recent_days: 0
          plugin_languages_recent_load: 999
          plugin_fortune: yes
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: yes
          filename: dist/github-metrics.svg
          output_action: none

      - name: Copy metrics output to workspace
        run: mkdir -p dist && cp /metrics_renders/dist/github-metrics.svg dist/

      - name: Push github-metrics.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v5.0.0
        with:
          target_branch: output-metrics
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
