name: Generate metrics

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_display: large
          config_octicon: yes
          config_timezone: Europe/Warsaw
          config_twemoji: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_other: no
          plugin_languages_limit: 999 
          repositories_forks: yes
